version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.4.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'True'
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
      - ./plugins:/root/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["webserver", "--port", "8080"]

  scheduler:
    image: apache/airflow:2.4.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'True'
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
      - ./plugins:/root/airflow/plugins
    depends_on:
      - postgres
    command: ["scheduler"]

  airflow-init:
    image: apache/airflow:2.4.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'your_fernet_key'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'True'
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
      - ./plugins:/root/airflow/plugins
    depends_on:
      - postgres
    entrypoint: ["airflow", "db", "init"]

volumes:
  postgres-db-volume:
